# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  latitude: !secret latitude                                        
  longitude: !secret longitude
  elevation: !secret elevation
  time_zone: !secret time_zone
  external_url: !secret base_url_public
  internal_url: !secret base_url_public
  
default_config:

# Text to speech
tts:
  - platform: google_translate
    cache: true
    service_name: google_say
    language: 'it'

group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
panel_custom: !include panel_custom.yaml
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
timer: !include timer.yaml
cover: !include cover.yaml
logger: !include logger.yaml
rest_command: !include rest_command.yaml
telegram_bot: !include telegram_bot.yaml
switch: !include switch.yaml
plant: !include plant.yaml
#packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named  themes/

lovelace:
  mode: yaml

# duck DNS
http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

#OK
#weather:
#  - platform: darksky
#    api_key: !secret darksky_api
#    mode: daily

vacuum:
  - platform: xiaomi_miio
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token 
    name: aspirapolvere

fan:
  - platform: xiaomi_miio
    host: !secret xiaomi_miio_ip
    token: !secret xiaomi_miio_token
    model: zhimi.airpurifier.mb3
    name: Air Purifier

#KO
#ffmpeg:
#  ffmpeg_bin: /usr/bin/ffmpeg
#camera:
#  - platform: mjpeg
#    name: OctoPrint Longer 4PRO
#    still_image_url: http://octoprint.local/webcam/?action=snapshot
#    mjpeg_url: http://octoprint.local/webcam/?action=stream

alarm_control_panel:
  - platform: manual
    name: Allarme
    code: 1234
    arming_time: 10
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

google_assistant:
  project_id: home-assistant-268211
  service_account: !include home-assistant-268211-f4b9012c2bd5.json
  exposed_domains:
    - scene
    - script

notify:
  - name: lorenzo
    platform: telegram
    chat_id: !secret telegram_id_lorenzo
  - name: luana
    platform: telegram
    chat_id: !secret telegram_id_luana
  - name: famiglia
    platform: group
    services:
      - service: lorenzo
      - service: luana

camera:
  - platform: mjpeg
    mjpeg_url: http://192.168.1.98/webcam/?action=stream
    name: "Octoprint"

climate:
  - platform: smartir
    name: Condizionatore Salotto
    controller_data: remote.broadlink_remote
    device_code: !secret device_code

#OK
octoprint:
  host: !secret octoprint_host
  port: !secret octoprint_port
  api_key: !secret octoprint_token
  bed: true
  number_of_tools: 1

     
modbus:
  name: hub1
  type: serial
  method: rtu
  #port: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_00000000-if00-port0
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
  #port: /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0
  baudrate: 4800
  stopbits: 1
  bytesize: 8
  parity: N

device_tracker:
  - platform: ping
    hosts:
      hostone: !secret hostone_ip

