title: MrNight House
icon: mdi:home-city-outline
#background: center / cover no-repeat url("/local/backgrounds/background-15.gif") fixed 
resources:
  - url: /local/custom_ui/lib/battery-entity.js?v=1
    type: module
  - url: /local/custom_ui/lib/vertical-stack-in-card.js?v=0.3.3
    type: js
  - url: /local/custom_ui/lib/auto-entities.js
    type: module
  - url: /local/custom_ui/lib/button-card.js
    type: module
  - url: /local/custom_ui/lib/mini-graph-card-bundle.js?v=0.9.2
    type: module
  - url: /local/custom_ui/lib/air-filter-card.js
    type: module
  - url: /local/custom_ui/lib/xiaomi-vacuum-card.js?v=3.0.1
    type: module
  - url: /local/custom_ui/lib/mini-media-player-bundle.js?v=1.9.1
    type: module
  - url: /local/custom_ui/lib/bar-card.js
    type: module
  - url: /local/custom_ui/lib/slider-entity-row.js
    type: module
  - url: /local/floorplan/floorplan-card.js?v=1.1.14
    type: module

views:
  - !include lovelace/tabs/home.yaml
  - !include lovelace/tabs/environment.yaml
  - !include lovelace/tabs/light.yaml
  #- !include lovelace/tabs/airpurifier.yaml
  - !include lovelace/tabs/covers.yaml
  - !include lovelace/tabs/automation.yaml
  - !include lovelace/tabs/battery.yaml
  - !include lovelace/tabs/maintenance.yaml
  - !include lovelace/tabs/alarm.yaml
  #- !include lovelace/tabs/cam.yaml
  - !include lovelace/tabs/floorplan.yaml
  - !include lovelace/tabs/mobile-device.yaml
  # !include lovelace/tabs/plant.yaml
  #- !include lovelace/tabs/coronavirus.yaml 
  - !include lovelace/tabs/baby.yaml 
  
     

  - icon: mdi:test-tube
    id: experimental
    title: Experimental
    panel: true
    cards:
      #- type: glance
      #  entities:
      #  - entity: light.rele2wayc_01
      #    name: Pompa 1
      #    icon: 'mdi:water-pump'
      #    show_state: false
      #    tap_action:
      #      action: toggle
      #  - entity: light.rele2wayc_02
      #    name: Pompa 2
      #    icon: 'mdi:water-pump'
      #    show_state: false
      #    tap_action:
      #      action: toggle
      - type: custom:vertical-stack-in-card
        title: Purificatore D'aria
        cards:
          - type: glance
            entities:
              - entity: sensor.octoprint_current_state
              - entity: sensor.octoprint_job_percentage
              - entity: sensor.octoprint_time_elapsed
              - entity: sensor.octoprint_time_remaining
              - entity: sensor.octoprint_target_bed_temp
              - entity: sensor.octoprint_actual_bed_temp
              - entity: sensor.octoprint_actual_tool0_temp
              - entity: sensor.octoprint_target_tool0_temp
              - entity: sensor.octoprint_print_file
              - entity: switch.octoprint_cancel_print
              - entity: switch.octoprint_emergency_stop
              - entity: switch.octoprint_pause_print
              - entity: switch.octoprint_shutdown_system
          - type: horizontal-stack
            title: Lights
            cards:  
              - type: gauge
                entity: sensor.octoprint_actual_tool0_temp
                name: Extrus
                max: 210
                min: 0
                severity:
                  green: 200
                  yellow: 150
                  red: 100
              - type: gauge
                entity: sensor.octoprint_actual_bed_temp
                name: Bed
                max: 70
                min: 0
                severity:
                  green: 60
                  yellow: 40
                  red: 20
                
            